return {
  {
    "fzf-lua",
    event = { "DeferredUIEnter" },
    after = function()
      local fzf = require("fzf-lua")
      vim.keymap.set("n", "<leader>ff", function()
        fzf.files()
      end, { desc = "Fuzzy find files" })
      vim.keymap.set("n", "<leader>fg", function()
        fzf.live_grep()
      end, { desc = "Fuzzy find grep" })
      vim.keymap.set("n", "<leader>fb", function()
        fzf.buffers()
      end, { desc = "Fuzzy find buffers" })
      vim.keymap.set("n", "<leader>fh", function()
        fzf.help_tags()
      end, { desc = "Fuzzy find help tags" })
      vim.keymap.set("n", "<leader>fr", function()
        fzf.registers()
      end, { desc = "Fuzzy find registers" })
      vim.keymap.set("n", "<leader>ft", function()
        fzf.tags()
      end, { desc = "Fuzzy find tags" })
      vim.keymap.set("n", "<leader>fw", function()
        fzf.lsp_workspace_symbols()
      end, { desc = "Fuzzy find workspace symbols" })
      vim.keymap.set("n", "<leader>fW", function()
        fzf.lsp_document_symbols()
      end, { desc = "Fuzzy find document symbols" })
      vim.keymap.set("n", "<leader>f/", function()
        fzf.command_history()
      end, { desc = "Fuzzy find command history" })
      vim.keymap.set("n", "<leader>f:", function()
        fzf.search_history()
      end, { desc = "Fuzzy find search history" })
      vim.keymap.set("n", "<leader>f?", function()
        fzf.keymaps()
      end, { desc = "Fuzzy find keymaps" })
      vim.keymap.set("n", "<leader>f<space>", function()
        fzf.resume()
      end, { desc = "Fuzzy find resume" })
    end,
  },
}
