{pkgs, ...}: {
  xdg.configFile."matugen/templates/i3lock-colors.sh" = {
    executable = true;
    text = ''
      #!/bin/sh
      # This file is generated by Matugen

      ${pkgs.i3lock-color}/bin/i3lock-color \
        -n \
        --blur 5 \
        --clock \
        --time-str="%H:%M:%S" \
        --date-str="%Y-%m-%d" \
        \
        --inside-color={{colors.surface.default.hex}} \
        --ring-color={{colors.primary.default.hex}} \
        --line-color={{colors.surface.default.hex}} \
        --keyhl-color={{colors.tertiary.default.hex}} \
        --bshl-color={{colors.error.default.hex}} \
        \
        --verif-color={{colors.primary.default.hex}} \
        --wrong-color={{colors.error.default.hex}} \
        \
        --time-color={{colors.on_surface.default.hex}} \
        --date-color={{colors.on_surface.default.hex}}
    '';
  };
}
