{
  xdg.configFile."matugen/templates/wlogout.css" = {
    text = ''
      /* Generated by Matugen - GTK3 Color Variables */
      @define-color surface_bg rgba({{ colors.surface.default.red }}, {{ colors.surface.default.green }}, {{ colors.surface.default.blue }}, 0.69);
      @define-color primary_accent {{ colors.primary.default.hex }};
      @define-color on_surface {{ colors.on_surface.default.hex }};
      @define-color hover_bg rgba({{ colors.primary_container.default.red }}, {{ colors.primary_container.default.green }}, {{ colors.primary_container.default.blue }}, 0.3);
    '';
  };
}
