[config]
version_check = true

[templates.foot]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-foot.ini'
output_path = '~/.config/foot/foot-colors.ini'

[templates.gtk3]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.discord]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-discord.css'
output_path = '~/.config/vesktop/themes/midnight-dis.css'

[templates.pywalfox]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-pywalfox.json'
output_path = '~/.cache/wal/colors.json'
# post_hook = 'pywalfox update'

[templates.yazi]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.hyprland]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.starship]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-starship.toml'
output_path = '~/.config/starship.toml'

[templates.qt5ct]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-kvantum.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantumSvg]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-kvantum.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.sequences]
input_path = '~/beeb5kSystem/modules/home-manager/matugen/templates/sequences.sh'
output_path = '~/.config/sequences.sh'
post_hook = "terminal-change-color"

[templates.quickshell]
input_path = "~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-quickshell.qml"
output_path = "~/Downloads/hyprcrow-main/.config/quickshell/Data/Colors.qml"

[templates.anyrun]
input_path = "~/beeb5kSystem/modules/home-manager/matugen/templates/matugen-anyrun.css"
output_path = "~/.config/anyrun/style.css"
