{
  imports = [
    ./eww
    ./neovim/default.nix
    ./river/default.nix
    ./btop.nix
    ./desktop-entries.nix
    ./file-manager.nix
    ./firefox.nix
    ./fonts.nix
    ./wofi.nix
    ./git.nix
    ./htop.nix
    ./mako.nix
    ./obs.nix
    ./satty.nix
    ./stylix.nix
    ./zsh.nix
    ./tmux.nix
    ./foot.nix
  ];
}
